{% set version = "0.9.5" %}

package:
  name: bmcs
  version: {{ version }}

source:
  path: ./ 

build:
  entry_points: 
    - bmcs = bmcs.scripts.bmcs_app:run_bmcs_launcher
  noarch: python
  number: 0

requirements:
  host:
    - python
  run:
    - scipy
    - scipy
    - ipywidgets
    - matplotlib
    - mayavi

about:
  home: https://github.com/simvisage/bmcs
  license: MIT
  summary: 'Brittle-matrix composite structures'
  description: |
    Brittle-matrix composite structure.
  dev_url: https://github.com/simvisage/bmcs
  doc_url: https://github.com/pypi/bmcs

